# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/node:15.6.0
    steps:
      - checkout
      - run:
          name: Publish package
          command: |
            npm publish --access public -_authToken=$NPM_PUBLISH_TOKEN
workflows:
  version: 2
  commit:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/